apiVersion: apps/v1
kind: Deployment
metadata:
  name: insta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insta
  template:
    metadata:
      labels:
        app: insta
    spec:
      containers:
      - name: insta
        image: vishnugpd/insta
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: insta
spec:
  selector:
    app: insta
  ports:
  - port: 80
    targetPort: 80
  type: NodePort

